name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 13.x]
        os: [windows-2019]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update node-gyp to fix nodejs/node-gyp#1933
        run: |
          $nodeInstall = Split-Path((Get-Command node).Path)
          cd "$nodeInstall/node_modules/npm"
          npm update node-gyp
      - run: yarn install --frozen-lockfile
      - run: yarn run lint
      - run: yarn run build
